version: '3'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=DEBUG
    networks:
      - site1
      - site2
    ports:
      - '8080:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mariadb:10.2
    ports:
      - 3306:3306
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: db
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - default
      - site1
      - site2

  mailhog:
    image: mailhog/mailhog
    container_name: "mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.localhost'
    networks:
      - default
      - site1
      - site2


networks:
  site1:
    external: 
      name: site2_default
  site2:
    external:
      name: site2_default

volumes:
  dbvolume: